execution:
  celery-k8s:
    config:
      image_pull_policy: "Always"
      repo_location_name: "example_repo"

resources:
  io_manager:
    config:
      s3_bucket: "sheenflow-test"
      s3_prefix: "sheenflow-celery-k8s"
