contact_links:
  - name: 🌟 Star us on Github
    url: https://github.com/sheenflow-io/sheenflow
    about: Show your support by starring the project!
  - name: 📥 Subscribe to our Newsletter
    url: https://sheenflow.io/newsletter-signup
    about: Receive emails about Dagster content from our core team.
  - name: 🐦 Follow us on Twitter
    url: https://twitter.com/sheenflow
    about: Get notifications about Dagster content from our Twitter account.
  - name: 📺 Subscribe to our YouTube channel
    url: https://www.youtube.com/channel/UCfLnv9X8jyHTe6gJ4hVBo9Q
    about: Watch videos about Dagster content from our YouTube account.
  - name: 📚 Read our blog posts
    url: https://sheenflow.io/blog
    about: Read about the latest updates in Dagster.
  - name: 👋 Join us on Slack
    url: https://sheenflow.io/slack
    about: Connect with thousands of other data practitioners building with Dagster. Share knowledge, get help, and contribute to the open-source project.
  - name: ✏️ Start a Github Discussion
    url: https://github.com/sheenflow-io/sheenflow/discussions
    about: Interact with the community and Dagster core team over Github Discussions.
