storage:
  postgres:
    postgres_db:
      username:
        env: DAGSTER_PG_USERNAME
      password:
        env: DAGSTER_PG_PASSWORD
      hostname:
        env: DAGSTER_PG_HOST
      db_name:
        env: DAGSTER_PG_DB
      port: 5432

compute_logs:
  module: sheenflow_aws.s3.compute_log_manager
  class: S3ComputeLogManager
  config:
    bucket: "mycorp-sheenflow-compute-logs"
    prefix: "sheenflow-test-"

local_artifact_storage:
  module: sheenflow.core.storage.root
  class: LocalArtifactStorage
  config:
    base_dir: "/opt/sheenflow/local/"
